/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DoAn;
import DoAn.DaTa.Connect;
import DoAn.Process.*;
import java.sql.*; 
import javax.swing.*;
/**
 *
 * @author Long Y
 */
public class Index extends javax.swing.JFrame {
     public static String sql="SELECT * FROM `xemay` WHERE 1 LIMIT 10";
   public static String maxe;//Lưu tạm khi nhấn lên dòng trong bảng dùng cho update và delete.
   public void ProcessCrt(boolean b)
   {
       
       this.btnThem.setEnabled(b);
       this.btnSua.setEnabled(b);
       this.btnXoa.setEnabled(b);
   }
   
    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        showCT();
        ProcessCrt(false);
    }
     public void showCT()
    {
        UpdataTable.LoadDaTa(sql, tbXeMay);
        this.lblTongXe.setText("Tổng số có "+this.tbXeMay.getRowCount()+" Xe máy");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTrangChu = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        txtTimXe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLoaiXe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGiaXe = new javax.swing.JTextField();
        txtNgaySX = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMauXe = new javax.swing.JTextField();
        txtHangSX = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnThemMoi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaXe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbXeMay = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lblTongXe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm Kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        txtTimXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimXeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Thông Tin Xe Máy");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Xe Máy"));

        jLabel4.setText("Tên Xe");

        jLabel5.setText("Loại Xe");

        jLabel6.setText("Giá Xe");

        jLabel7.setText("Ngày SX");

        jLabel8.setText("Màu Xe");

        jLabel9.setText("Hãng SX");

        btnThemMoi.setText("Thêm Mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã Xe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenXe, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtLoaiXe)
                    .addComponent(txtGiaXe)
                    .addComponent(txtNgaySX)
                    .addComponent(txtMauXe)
                    .addComponent(txtHangSX)
                    .addComponent(txtMaXe)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGiaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNgaySX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnThemMoi)
                .addContainerGap())
        );

        tbXeMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbXeMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbXeMayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbXeMay);

        btnThem.setForeground(new java.awt.Color(51, 51, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setForeground(new java.awt.Color(204, 0, 204));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(255, 51, 51));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        lblTongXe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTongXe.setForeground(new java.awt.Color(255, 51, 51));
        lblTongXe.setText("Tổng số Xe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(txtTimXe, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTim))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTongXe, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(970, 970, 970))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnTrangChu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnTrangChu)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTongXe)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        showCT();
        ProcessCrt(false);
        this.txtTimXe.setText(null);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if(this.txtTimXe.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Bạn cần nhập từ khóa vào để kiếm","Thông báo",1);
        }
        else
        {
            String sql="SELECT * FROM `xemay` WHERE maXe LIKE '%"+txtTimXe.getText()+"%' OR tenXe LIKE '%"+txtTimXe.getText()+"%'";
            UpdataTable.LoadDaTa(sql, tbXeMay);
            this.lblTongXe.setText("Có: "+this.tbXeMay.getRowCount()+" xe tìm thấy");
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtTimXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimXeActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        ProcessCrt(false);
        this.btnThem.setEnabled(true);
        this.txtMaXe.setText(null);
        this.txtTenXe.setText(null);
        this.txtLoaiXe.setText(null);
        this.txtGiaXe.setText(null);
        this.txtNgaySX.setText(null);
        this.txtMauXe.setText(null);
        this.txtHangSX.setText(null);
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void tbXeMayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbXeMayMouseClicked
        ProcessCrt(true);
        this.btnThem.setEnabled(false);
        try
        {
            int row =this.tbXeMay.getSelectedRow();//Lấy dòng hiện tại đang nhấn
            String IDrow=(this.tbXeMay.getModel().getValueAt(row, 0).toString());//Láy giá trị ở dòng vừa nhấn
            //Láy giá trị đổi ra string
            String sql1="SELECT * FROM qlxemay.xemay WHERE maXe='"+IDrow+"'";
            ResultSet rs=UpdataTable.ShowTextField(sql1);
            //Đõ dư liệu tại dòng IDrow:
            if(rs.next())
            {
                maxe=rs.getString("maXe");
                this.txtMaXe.setText(rs.getString("maXe"));
                this.txtTenXe.setText(rs.getString("tenXe"));
                this.txtLoaiXe.setText(rs.getString("loaiXe"));
                this.txtGiaXe.setText(rs.getString("giaXe"));
                this.txtNgaySX.setText(rs.getString("ngaySX"));
                this.txtMauXe.setText(rs.getString("mauXe"));
                this.txtHangSX.setText(rs.getString("hangSX"));

            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbXeMayMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(this.txtMaXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để mã Xe trống","Thông báo",1);
        else
        if(this.txtMaXe.getText().length()>10)
        JOptionPane.showMessageDialog(null, "Mã Xe không được quá 10 kí tự","Thông báo",1);
        else
        if(this.txtTenXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Tên Xe trống","Thông báo",1);
        else
        if(this.txtLoaiXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Loại Xe trống","Thông báo",1);
        else
        if(this.txtGiaXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Giá Xe trống","Thông báo",1);
        else
        if(this.txtNgaySX.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Ngày SX Xe trống","Thông báo",1);
        else
        if(this.txtMauXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Màu Xe trống","Thông báo",1);
        else
        if(this.txtHangSX.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Hãng SX Xe trống","Thông báo",1);
        else
        {
            XeMay.InsertXeMay(this.txtMaXe.getText().trim(), this.txtTenXe.getText(),this.txtLoaiXe.getText(),this.txtGiaXe.getText(),this.txtNgaySX.getText(),this.txtMauXe.getText(),this.txtHangSX.getText());
            showCT();
            ProcessCrt(false);
            
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        if(this.txtMaXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để mã Xe trống","Thông báo",1);
        else
        if(this.txtMaXe.getText().length()>10)
        JOptionPane.showMessageDialog(null, "Mã Xe không được quá 10 kí tự","Thông báo",1);
        else
        if(this.txtTenXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Tên Xe trống","Thông báo",1);
        else
        if(this.txtLoaiXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Loại Xe trống","Thông báo",1);
        else
        if(this.txtGiaXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Giá Xe trống","Thông báo",1);
        else
        if(this.txtNgaySX.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Ngày SX Xe trống","Thông báo",1);
        else
        if(this.txtMauXe.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Màu Xe trống","Thông báo",1);
        else
        if(this.txtHangSX.getText().length()==0)
        JOptionPane.showMessageDialog(null, "Không được để Hãng SX Xe trống","Thông báo",1);
        else
        {
            XeMay.UpdateXeMay(maxe, this.txtMaXe.getText().trim(), this.txtTenXe.getText(),this.txtLoaiXe.getText(),this.txtGiaXe.getText(),this.txtNgaySX.getText(),this.txtMauXe.getText(),this.txtHangSX.getText());
            showCT();
            ProcessCrt(false);
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(this.txtMaXe.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn xe để xóa","Thông báo",1);
        }
        else
        {

            if(JOptionPane.showConfirmDialog(null, "Bạn có muốn chắc chắn xóa " +maxe+ " hay không? ","Thông báo",2)==0)
            {
                XeMay.DeleteXeMay(maxe);
                showCT();
                ProcessCrt(false);

            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTongXe;
    private javax.swing.JTable tbXeMay;
    private javax.swing.JTextField txtGiaXe;
    private javax.swing.JTextField txtHangSX;
    private javax.swing.JTextField txtLoaiXe;
    private javax.swing.JTextField txtMaXe;
    private javax.swing.JTextField txtMauXe;
    private javax.swing.JTextField txtNgaySX;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtTimXe;
    // End of variables declaration//GEN-END:variables
}
